name: Build

on: [push, pull_request]

jobs:
  
  windows:       
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5 mingw-w64-x86_64-libelf
      - name: win-build
        run: |
          mkdir build
          cd build
          qmake ..
          make
